version: 2

install-jq: &install-jq
  name: Install jq
  command: |
    curl -fsSL -o /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
    chmod +x /usr/local/bin/jq

test-ubuntu: &test-ubuntu
  steps:
    - checkout
    - run: cat /etc/*-release
    - run: apt-get update -qq && apt-get install -y apt-transport-https curl
    - run:
        <<: *install-jq
    - run: DIST=ubuntu ./test/test-packages.sh

test-debian: &test-debian
  steps:
    - checkout
    - run: cat /etc/*-release
    - run: apt-get update -qq && apt-get install -y curl
    - run:
        <<: *install-jq
    - run: DIST=debian ./test/test-packages.sh

test-centos: &test-centos
  steps:
    - checkout
    - run: cat /etc/*-release
    - run:
        <<: *install-jq
    - run: DIST=centos ./test/test-packages.sh

test-opensuse: &test-opensuse
  steps:
    - checkout
    - run: cat /etc/*-release
    - run: zypper --quiet --non-interactive update && zypper --non-interactive install curl
    - run:
        <<: *install-jq
    - run: DIST=opensuse ./test/test-packages.sh

jobs:
  trusty:
    <<: *test-ubuntu
    environment:
      VER: '14.04'
    docker:
      - image: ubuntu:trusty
  xenial:
    <<: *test-ubuntu
    environment:
      VER: '16.04'
    docker:
      - image: ubuntu:xenial
  bionic:
    <<: *test-ubuntu
    environment:
      VER: '18.04'
    docker:
      - image: ubuntu:bionic
  focal:
    <<: *test-ubuntu
    environment:
      VER: '20.04'
    docker:
      - image: ubuntu:focal
  jessie:
    <<: *test-debian
    environment:
      VER: '8'
    docker:
      - image: debian:jessie
  stretch:
    <<: *test-debian
    environment:
      VER: '9'
    docker:
      - image: debian:stretch
  centos7:
    <<: *test-centos
    environment:
      VER: '7'
    docker:
      - image: centos:7
  centos8:
    <<: *test-centos
    environment:
      VER: '8'
    docker:
      - image: rockylinux:8
  opensuse42:
    <<: *test-opensuse
    environment:
      VER: '42.3'
    docker:
      - image: opensuse/leap:42.3
  opensuse15:
    <<: *test-opensuse
    environment:
      VER: '15.0'
    docker:
      - image: opensuse/leap:15.0
  opensuse152:
    <<: *test-opensuse
    environment:
      VER: '15.2'
    docker:
      - image: opensuse/leap:15.2
  opensuse153:
    <<: *test-opensuse
    environment:
      VER: '15.3'
    docker:
      - image: opensuse/leap:15.3
workflows:
  version: 2
  build:
    jobs:
      - trusty
      - xenial
      - bionic
      - focal
      - jessie
      - stretch
      - centos7
      - centos8
      - opensuse42
      - opensuse15
      - opensuse152
      - opensuse153
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - trusty
      - xenial
      - bionic
      - focal
      - jessie
      - stretch
      - centos7
      - centos8
      - opensuse42
      - opensuse15
      - opensuse152
      - opensuse153
